import Head from "next/head";
import Navbar from "@/components/Navbar";
import { motion } from "framer-motion";
import Header from "@/components/Header";
import About from "@/components/About";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  solid,
  regular,
  brands,
  icon,
} from "@fortawesome/fontawesome-svg-core/import.macro";
import Education from "@/components/Education";
import Projects from "@/components/Projects";
import Archive from "@/components/Archive";
import Contact from "@/components/Contact";
import Footer from "@/components/Footer";
import { LanguageContext } from "./context/language/LanguageContext";

export default function Home() {
  return (
    <>
      <Head>
        <title>Damián Rondinon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>
      <LanguageContext>
        <main className="w-full h-screen font-bodyFont bg-bodyColor text-textLight overflow-x-hidden overflow-y-scroll">
          <Navbar />
          <div className="w-full h-[88vh] xl:flex items-center gap-20 justify-between">
            <div className="h-[88vh] w-full mx-auto p-4">
              <Header />
              <About />
              <Projects />
              <Education />
              <Archive />
              {/* Blog */}
              <Contact />
              <Footer />
            </div>
          </div>
        </main>
      </LanguageContext>
    </>
  );
}
